import VueRouter from 'vue-router'

const routes = [
    {
        path:'/',
        redirect:'/login',
    },
    //登录页
    {
        path:'/login',
        name:'Login',
        component:()=>
            import('@/views/Login.vue')
    },
    //注册页
    {
        path:'/register',
        name:'Register',
        component:()=>
            import('@/views/Register.vue')
    },
    //主页
    {
        path:'/home',
        name:'Home',
        component:()=>
            import('@/views/Home.vue')
    },
    //商城页
    {
        path:'/shop',
        name:'Shop',
        component:()=>
            import('@/views/Shop.vue')
    },
    //TNR页
    {
        path:'/tnr',
        name:'Tnr',
        component:()=>
            import('@/views/Tnr.vue')
    },
    //我的
    {
        path:'/my',
        name:'My',
        component:()=>
            import('@/views/My.vue')
    },
    //领养简介页面
    {
        path:'/instruction',
        name:'Instruction',
        component:()=>
            import('@/views/Instruction.vue')
    },
    //选择地址
    {
        path:'/location',
        name:'Location',
        component:()=>
            import('@/views/Location.vue')
    },
    //搜索猫咪
    {
        path:'/searchcat',
        name:'SearchCat',
        component:()=>
            import('@/views/CatSearch.vue'),
    },
    //我要送养
    {
        path:'/send',
        name:'Send',
        component:()=>
            import('@/views/SendCat.vue'),
    },
    //领养反馈
    {
        path:'/feedback',
        name:'Feedback',
        component:()=>
            import('@/views/Feedback.vue'),
    },
    //我的领养反馈
    {
        path:'/myfeedback',
        name:'MyFeedback',
        component:()=>
            import('@/views/MyFeedback.vue'),
    },
    //发布反馈
    {
        path:'/sendfeedback',
        name:'SendFeedback',
        component:()=>
            import('@/views/SendFeedback.vue'),
    },
    //领养详情
    {
        path:'/adopt',
        name:'Adopt',
        component:()=>
            import('@/views/AdoptDetail.vue'),
    },
    //结算页面
    {
        path:'/payment',
        name:'Payment',
        component:()=>
            import('@/views/Payment.vue'),
    },
    //我的领养
    {
        path:'/myadopt',
        name:'MyAdopt',
        component:()=>
            import('@/views/MyAdopt.vue'),
    },
    //我的送养
    {
        path:'/mysend',
        name:'MySend',
        component:()=>
            import('@/views/MySend.vue'),
    },
    //申请TNR
    {
        path:'/sendtnr',
        name:'SendTnr',
        component:()=>
            import('@/views/SendTnr.vue'),
    },
    //我的TNR申请
    {
        path:'/mytnr',
        name:'MyTnr',
        component:()=>
            import('@/views/MyTnr.vue'),
    },
]

const router = new VueRouter({
    mode:'history',
    base:process.env.BASE_URL,
    routes,
})

export default router;